config/urls.py
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls


urlpatterns = [
    path("", include("pages.urls")),
    path("interviews/", include("interviews.urls")),
    path("users/", include("users.urls")),
    path("admin/", admin.site.urls),
] + debug_toolbar_urls()

interviews/urls.py
from django.urls import path
from . import views

app_name = "interviews"

urlpatterns = [
    path("", views.index, name="index"),
    path("new", views.new, name="new"),
    path("<int:id>", views.show, name="show"),
    path("<int:id>/edit", views.edit, name="edit"),
    path("<int:id>/delete", views.delete, name="delete"),
    path("<int:id>/comment", views.comment, name="comment"),
    path("<int:id>/favorite", views.favorite, name="favorite"),
]

pages/urls.py
from django.urls import path
from . import views

app_name = "pages"

urlpatterns = [
    path("", views.home, name="home"),
    path("about", views.about, name="about"),
    path("contact", views.contact, name="contact"),
    path("payment", views.payment, name="payment"),
    path("checkout", views.checkout, name="checkout"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("", views.index, name="index"),
    path("sign_up/", views.sign_up, name="sign_up"),
    path("sign_in/", views.sign_in, name="sign_in"),
    path("login/", views.create_session, name="login"),
    path("logout/", views.delete_session, name="logout"),
]

interviews/models.py
from django.db import models
from django.contrib.auth.models import User


class Interview(models.Model):
    company_name = models.CharField(max_length=100)
    position = models.CharField(max_length=50)
    interview_date = models.DateField(null=True)
    review = models.TextField()
    rating = models.PositiveSmallIntegerField(
        help_text="1 ~ 10 分，1 分最低、10 分最高",
    )
    result = models.CharField(max_length=100, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    favorited_by = models.ManyToManyField(
        User,
        through="FavoriteInterview",
        related_name="favorite_interviews",
    )


class Comment(models.Model):
    interview = models.ForeignKey(Interview, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class FavoriteInterview(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    interview = models.ForeignKey(Interview, on_delete=models.CASCADE)

interviews/forms.py
from django.forms import ModelForm, DateInput
from .models import Interview


class InterviewForm(ModelForm):
    class Meta:
        model = Interview
        fields = [
            "company_name",
            "position",
            "result",
            "rating",
            "review",
            "interview_date",
        ]
        labels = {
            "company_name": "公司名稱",
            "position": "職稱",
            "interview_date": "面試日期",
            "result": "面試結果",
            "rating": "評比",
            "review": "心得",
        }
        widgets = {
            "interview_date": DateInput({"type": "date"}),
        }

interviews/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Interview
from .forms import InterviewForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.contrib import messages


def index(request):
    if request.POST:
        form = InterviewForm(request.POST)
        interview = form.save(commit=False)
        interview.user = request.user
        interview.save()
        messages.success(request, "新增面試成功")
        return redirect("interviews:show", interview.id)
    else:
        interviews = Interview.objects.order_by("-id")
        return render(
            request,
            "interviews/index.html",
            {"interviews": interviews},
        )


@login_required
def show(request, id):
    interview = get_object_or_404(Interview, pk=id)

    if request.POST:
        form = InterviewForm(request.POST, instance=interview)
        form.save()
        messages.success(request, "面試已更新")
        return redirect("interviews:show", interview.id)
    else:
        comments = interview.comment_set.prefetch_related("user").order_by("-id")
        return render(
            request,
            "interviews/show.html",
            {"interview": interview, "comments": comments},
        )


@login_required
def new(req):
    form = InterviewForm()
    return render(req, "interviews/new.html", {"form": form})


@login_required
def edit(req, id):
    interview = get_object_or_404(Interview, pk=id)
    form = InterviewForm(instance=interview)
    return render(
        req,
        "interviews/edit.html",
        {
            "interview": interview,
            "form": form,
        },
    )


@login_required
def delete(req, id):
    interview = get_object_or_404(Interview, pk=id)
    interview.delete()

    messages.success(req, "面試已刪除")
    return redirect("interviews:index")


@require_POST
@login_required
def comment(request, id):
    interview = get_object_or_404(Interview, pk=id)
    interview.comment_set.create(
        content=request.POST["content"],
        user=request.user,
    )
    return redirect("interviews:show", interview.id)


@require_POST
@login_required
def favorite(request, id):
    interview = get_object_or_404(Interview, pk=id)
    favorites = request.user.favorite_interviews

    if favorites.filter(pk=interview.pk).exists():
        favorites.remove(interview)
    else:
        favorites.add(interview)

    return render(
        request,
        "interviews/favorite.html",
        {
            "user": request.user,
            "interview": interview,
        },
    )

pages/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
import braintree
from django.contrib import messages
from dotenv import load_dotenv
import os

load_dotenv()


def home(req):
    return render(req, "pages/home.html")


def about(req):
    return render(req, "pages/about.html")


def contact(req):
    return render(req, "pages/contact.html")


def payment(req):
    token = braintree_gateway().client_token.generate()
    return render(req, "pages/payment.html", {"token": token})


@require_POST
def checkout(request):
    result = braintree_gateway().transaction.sale(
        {
            "amount": 10,
            "payment_method_nonce": request.POST["nonce"],
        }
    )

    if result.is_success:
        # 把 User 的角色設定成 vip
        messages.success(request, "付款成功")
    else:
        messages.error(request, "付款失敗")

    return redirect("pages:home")


def braintree_gateway():
    return braintree.BraintreeGateway(
        braintree.Configuration(
            environment=braintree.Environment.Sandbox,
            merchant_id=os.getenv("MERCHANT_ID"),
            public_key=os.getenv("PUBLIC_KEY"),
            private_key=os.getenv("PRIVATE_KEY"),
        )
    )

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.views.decorators.http import require_POST
from django.urls import reverse
from django.contrib import messages


@require_POST
def index(req):
    form = UserCreationForm(req.POST)
    form.save()

    return redirect("pages:home")


def sign_in(req):
    next = req.GET.get("next", reverse("pages:home"))
    return render(req, "users/sign_in.html", {"next": next})


@require_POST
def create_session(req):
    username = req.POST.get("username")
    password = req.POST.get("password")

    user = authenticate(
        username=username,
        password=password,
    )

    if user is not None:
        login(req, user)

        next = req.POST.get("next", "pages:home")
        messages.success(req, "登入成功")
        return redirect(next)
    else:
        return redirect("users:sign_in")


@require_POST
def delete_session(req):
    logout(req)
    messages.success(req, "已登出")
    return redirect("pages:home")


def sign_up(req):
    form = UserCreationForm()
    return render(
        req,
        "users/sign_up.html",
        {
            "form": form,
        },
    )

interviews/templates/interviews/edit.html
<h1>編輯：{{ interview.company_name }}</h1>

<form action="{% url 'interviews:show' interview.id %}" method="post">
  {% csrf_token %}

  {% for field in form %}
    <div>
      {{ field.label_tag }}
      {{ field }}
      <div style="font-size: 10px">
        {{ field.help_text }}
      </div>
    </div>
  {% endfor %}

  <a href="{% url 'interviews:index' %}">回面試列表</a>
  <a href="{% url 'interviews:show' interview.id %}">回上頁</a>
  <input type="submit" value="更新" />
</form>

interviews/templates/interviews/favorite.html
{% if user in interview.favorited_by.all %}
  <button hx-swap="outerHTML"
          hx-post="{% url 'interviews:favorite' interview.id %}"
          class="btn btn-xs btn-neutral">已收藏</button>
{% else %}
  <button hx-swap="outerHTML"
          hx-post="{% url 'interviews:favorite' interview.id %}"
          class="btn btn-xs btn-ghost">收藏</button>
{% endif %}

interviews/templates/interviews/index.html
{% extends "layouts/default.html" %}

{% block main %}
  <h1 class="text-3xl">面試列表</h1>

  <a href="{% url 'interviews:new' %}" class="btn btn-neutral">新增面試</a>

  <ul>
  {% for interview in interviews %}
    <li>
      <a href="{% url 'interviews:show' interview.id %}">
        <section>
          <h2>{{ interview.position }}</h2>
          <h3>{{ interview.company_name }}</h3>
          <span>評價：{{ interview.rating }}/10</span>
        </section>
      </a>
    </li>
  {% endfor %}
  </ul>
{% endblock %}

interviews/templates/interviews/new.html
{% extends "layouts/default.html" %}

{% block main %}
  <header class="flex items-center gap-2 my-2 justify-between">
    <h1 class="text-3xl">新增面試</h1>
    <a href="{% url 'interviews:index' %}">→ 回面試列表</a>
  </header>

  <form action="/interviews/" method="post">
    {% csrf_token %}

    {% for field in form %}
      <div>
        {{ field.label_tag }}
        {{ field }}
        <div class="text-xs">
          {{ field.help_text }}
        </div>
      </div>
    {% endfor %}

    <input type="submit" value="新增" class="btn btn-neutral" />
  </form>

{% endblock %}

interviews/templates/interviews/show.html
{% extends "layouts/default.html" %}

{% block main %}
  {% include "interviews/favorite.html" with user=user interview=interview %}

  <h1 class="text-3xl">公司：{{ interview.company_name }}</h1>

  <div> {{ interview.rating }} / 10 </div>
  <p>
    {{ interview.review }}
  </p>

  <footer class="flex gap-2 my-2">
    <a href="{% url 'interviews:edit' interview.id %}" class="btn btn-sm">編輯</a>

    <form action="{% url 'interviews:delete' interview.id %}"
          method="post"
          onsubmit="return confirm('是否確認刪除？')">
      {% csrf_token %}
      <button class="btn btn-sm btn-error">刪除</button>
    </form>
  </footer>

  <ul class="list">
  {% for comment in comments %}
    <li class="my-1">
      {{ comment.user }} 說：<br />
      {{ comment.content|linebreaks }}
    </li>
  {% endfor %}
  </ul>

  <form method="post" action="{% url 'interviews:comment' interview.id %}">
    {% csrf_token %}
    <div class="flex flex-col gap-2">
      <textarea name="content" class="textarea"></textarea>
      <div>
        <button class="btn btn-sm">新增留言</button>
      </div>
    </div>
  </form>
{% endblock%}

pages/templates/home.html
<h1>Home</h1>
<h2>hi</h2>

pages/templates/pages/about.html
{% extends "layouts/default.html" %}

{% block main %}
  <h1>關於我們</h1>
{% endblock %}

pages/templates/pages/contact.html
{% extends "layouts/default.html" %}

{% block main %}
  <h1>聯絡我們</h1>
{% endblock %}

pages/templates/pages/home.html
{% extends "layouts/default.html" %}
{% load static %}

{% block main %}
  <h1>首頁</h1>
  <img src="{% static 'interviews/pudog.jpg' %}" />
{% endblock %}

pages/templates/pages/payment.html
{% extends "layouts/default.html" %}

{% block main %}
  <h1>付款</h1>

  <form x-data="braintree_form"
        action="/checkout"
        method="post"
        data-token="{{ token }}">
    {% csrf_token %}
    <div x-ref="dropin"></div>
    <input type="hidden" x-ref="nonce" name="nonce" />
    <button type="submit" class="btn btn-neutral">付款</button>
  </form>
{% endblock %}

templates/layouts/default.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>面試</title>
    <link href="{% static 'assets/styles/app.css' %}" rel="stylesheet" type="text/css" />
    <script type="module" src="{% static 'assets/scripts/app.js' %}"></script>
  </head>
  <body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
    {% include "shared/navbar.html" %}
    {% include "shared/messages.html" %}

    <main class="container mx-auto my-6">{% block main %}{% endblock %}</main>

    {% include "shared/footer.html" %}
  </body>
</html>

templates/shared/footer.html
<footer class="footer sm:footer-horizontal bg-base-300 text-base-content p-10">
  <nav>
    <h6 class="footer-title">Services</h6>
    <a class="link link-hover">Branding</a>
    <a class="link link-hover">Design</a>
    <a class="link link-hover">Marketing</a>
    <a class="link link-hover">Advertisement</a>
  </nav>
  <nav>
    <h6 class="footer-title">Company</h6>
    <a class="link link-hover">About us</a>
    <a class="link link-hover">Contact</a>
    <a class="link link-hover">Jobs</a>
    <a class="link link-hover">Press kit</a>
  </nav>
  <nav>
    <h6 class="footer-title">Social</h6>
    <div class="grid grid-flow-col gap-4">
      <a>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          class="fill-current">
          <path
            d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"></path>
        </svg>
      </a>
      <a>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          class="fill-current">
          <path
            d="M19.615 3.184c-3.604-.246-11.631-.245-15.23 0-3.897.266-4.356 2.62-4.385 8.816.029 6.185.484 8.549 4.385 8.816 3.6.245 11.626.246 15.23 0 3.897-.266 4.356-2.62 4.385-8.816-.029-6.185-.484-8.549-4.385-8.816zm-10.615 12.816v-8l8 3.993-8 4.007z"></path>
        </svg>
      </a>
      <a>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="24"
          height="24"
          viewBox="0 0 24 24"
          class="fill-current">
          <path
            d="M9 8h-3v4h3v12h5v-12h3.642l.358-4h-4v-1.667c0-.955.192-1.333 1.115-1.333h2.885v-5h-3.808c-3.596 0-5.192 1.583-5.192 4.615v3.385z"></path>
        </svg>
      </a>
    </div>
  </nav>
</footer>

templates/shared/messages.html
{% if messages %}
  {% for message in messages %}
    <template x-data="message" x-if="show">
      <div role="alert" class="alert alert-{{ message.tags }}">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 shrink-0 stroke-current" fill="none" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        <span>{{ message }}</span>
        <button @click="close" class="btn btn-xs">X</button>
      </div>
    </template>
  {% endfor %}
{% endif %}

templates/shared/navbar.html
<div class="navbar bg-base-100 shadow-sm">
  <div class="navbar-start">
    <div class="dropdown">
      <div tabindex="0" role="button" class="btn btn-ghost lg:hidden">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"> <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h8m-8 6h16" /> </svg>
      </div>
      <ul
        tabindex="0"
        class="menu menu-sm dropdown-content bg-base-100 rounded-box z-1 mt-3 w-52 p-2 shadow">
        <li><a>面試列表</a></li>
      </ul>
    </div>
    <a href="{% url 'pages:home' %}" class="btn btn-ghost text-xl">MSC</a>
  </div>
  <div class="navbar-center hidden lg:flex">
    <ul class="menu menu-horizontal px-1">
      <li><a href="{% url 'interviews:index' %}">面試列表</a></li>
    </ul>
  </div>
  <div class="navbar-end gap-2">
    {% if user.is_authenticated %}
      <form action="{% url 'users:logout' %}" method="POST">
        {% csrf_token %}
        <button class="btn btn-neutral">登出</button>
      </form>
    {% else %}
      <a href="{% url 'users:sign_up' %}" class="btn btn-neutral">註冊</a>
      <a href="{% url 'users:sign_in' %}" class="btn">登入</a>
    {% endif %}
  </div>
</div>

users/templates/users/sign_in.html
{% extends "layouts/default.html" %}

{% block main %}
  <h1 class="text-3xl">登入</h1>
  <form method="post" class="flex flex-col gap-2" action="{% url 'users:login' %}">
    {% csrf_token %}

    <input type="hidden" name="next" value="{{ next }}" />

    <fieldset class="fieldset">
      <legend class="fieldset-legend">帳號</legend>
      <input type="text" class="input" name="username" />
    </fieldset>

    <fieldset class="fieldset">
      <legend class="fieldset-legend">密碼</legend>
      <input type="password" class="input" name="password" />
    </fieldset>

    <div>
      <button class="btn btn-neutral">登入</button>
    </div>
  </form>
{% endblock %}

users/templates/users/sign_up.html
{% extends "layouts/default.html" %}

{% block main %}
  <h1 class="text-3xl">註冊</h1>
  <form method="post" action="{% url 'users:index' %}">
    {% csrf_token %}

    {% for field in form %}
      <div>
        {{ field.label_tag }}
        {{ field }}
      </div>
    {% endfor %}

    <button class="btn btn-neutral">註冊</button>
  </form>
{% endblock %}